### ISSUE TITLE
can not use su command after install

### ISSUE THREAD

**Issue by sevenshal** [Gnurou/busybox-android#3]
/system/bin/su -> /system/xbin/su -> busybox su

but busybox echo 2000:10074: applet not found

**Comment by Gnurou** [comment]
This package is very old and I have not updated for a while. I would expect it to fail on the latest Android versions. My best advice is to try and find another equivalent but more up-to-date package, there has to be plenty. I would be grateful if you could suggest a good one so I can update the README to point to it instead of having more users wasting time trying this package! :)
